# Advance Programming Assignment 20

**1. Create a function based on the input and output. Look at the examples, there is a pattern.**  
>**Examples**  
secret("p.one.two.three") ➞ "<p class='one two three'></p>"  
secret("p.one") ➞ "<p class='one'></p>"  
secret("p.four.five") ➞ "<p class='four five'></p>"  

In [9]:
def secret(input_str:str)-> str:
    input_list = input_str.split(".")
    tag = input_list[0]
    class_name = " ".join(input_list[1:])
    output = f"<{tag} class='{class_name}'></{tag}>"
    return output

In [10]:
secret("p.one.two.three")

"<p class='one two three'></p>"

In [11]:
secret("p.one")

"<p class='one'></p>"

In [12]:
secret("p.four.five")

"<p class='four five'></p>"

**2. Create a function which counts how many lone 1s appear in a given number. Lone means the number doesn't appear twice or more in a row.**  

>**Examples**  
count_lone_ones(101) ➞ 2  
count_lone_ones(1191) ➞ 1  
count_lone_ones(1111) ➞ 0  
count_lone_ones(462) ➞ 0  

In [51]:
def count_lone_ones(num:int)->int:
    num_str = str(num)
    count = 0
    for i in range(len(num_str)):
        if num_str[i]=="1":
            if i == 0 and num_str[i+1]!="1":
                count +=1
            elif i == len(num_str)-1 and num_str[i-1]!="1":
                count +=1
            elif num_str[i-1]!="1" and num_str[i+1]!="1":
                count +=1
    return count

In [52]:
count_lone_ones(101)

2

In [53]:
count_lone_ones(1191) 

1

In [54]:
count_lone_ones(1111)

0

In [56]:
count_lone_ones(1010101011)

4

**3. Write a method that accepts two integer parameters rows and cols. The output is a 2d array of numbers displayed in column-major order, meaning the numbers shown increase sequentially down each column and wrap to the top of the next column to the right once the bottom of the current column is reached.**  

>**Examples**  

printGrid(3, 6) ➞ [  
  [1, 4, 7, 10, 13, 16],  
  [2, 5, 8, 11, 14, 17],  
  [3, 6, 9, 12, 15, 18]  
]  

printGrid(5, 3) ➞ [  
  [1, 6, 11],  
  [2, 7, 12],  
  [3, 8, 13],  
  [4, 9, 14],  
  [5, 10, 15]  
]  

printGrid(4, 1) ➞ [  
  [1],  
  [2],  
  [3],  
  [4]  
]  

In [23]:
import numpy as np
def printGrid(rows:int,cols:int)->list:
    grid_num = [i for i in range(1, (rows*cols)+1)]
    grid = np.asarray(grid_num,dtype=int).reshape(rows,cols,order="F")
    return grid

In [24]:
printGrid(3, 6)

array([[ 1,  4,  7, 10, 13, 16],
       [ 2,  5,  8, 11, 14, 17],
       [ 3,  6,  9, 12, 15, 18]])

In [25]:
printGrid(5, 3)

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

In [26]:
printGrid(4, 1)

array([[1],
       [2],
       [3],
       [4]])

**4. Given a list of integers, return the smallest positive integer not present in the list.**  

Here is a representative example. Consider the list:

[-2, 6, 4, 5, 7, -1, 7, 1, 3, 6, 6, -2, 9, 10, 2, 2]

After reordering, the list becomes:

[-2, -2, -1, 1, 2, 2, 3, 4, 5, 6, 6, 6, 7, 7, 9, 10]

from which we see that the smallest missing positive integer is 8.

>**Examples**  
min_miss_pos([-2, 6, 4, 5, 7, -1, 1, 3, 6, -2, 9, 10, 2, 2]) ➞ 8  
    --> # After sorting, list becomes [-2, -2, -1, 1, 2, 2, 3, 4, 5, 6, 6, 7, 9, 10]  
    --> # So the smallest missing positive integer is 8  
min_miss_pos([5, 9, -2, 0, 1, 3, 9, 3, 8, 9]) ➞ 2  
    --> # After sorting, list becomes [-2, 0, 1, 3, 3, 5, 8, 9, 9, 9]  
    --> # So the smallest missing positive integer is 2  
min_miss_pos([0, 4, 4, -1, 9, 4, 5, 2, 10, 7, 6, 3, 10, 9]) ➞ 1  
    --> # After sorting, list becomes [-1, 0, 2, 3, 4, 4, 4, 5, 6, 7, 9, 9, 10, 10]  
    --> # So the smallest missing positive integer is 1  


In [37]:
def min_miss_pos(int_list:list)->int:
    int_list = set([i for i in int_list if i>0])
    max_num = max(int_list)
    for num in range(1,max_num+1):
        if num not in int_list:
            return num
    return None

In [34]:
min_miss_pos([-2, 6, 4, 5, 7, -1, 1, 3, 6, -2, 9, 10, 2, 2])

8

In [35]:
min_miss_pos([5, 9, -2, 0, 1, 3, 9, 3, 8, 9])

2

In [36]:
min_miss_pos([0, 4, 4, -1, 9, 4, 5, 2, 10, 7, 6, 3, 10, 9])

1

**5. Google is launching a network of autonomous pizza delivery drones and wants you to create a flexible rewards system (Pizza Points™) that can be tweaked in the future. The rules are simple: if a customer has made at least N orders of at least Y price, they get a FREE pizza!**  

**Create a function that takes a dictionary of customers, a minimum number of orders and a minimum order price. Return a list of customers that are eligible for a free pizza.**  

>**Examples**  

customers = {
  "Batman": [22, 30, 11, 17, 15, 52, 27, 12],
  "Spider-Man": [5, 17, 30, 33, 40, 22, 26, 10, 11, 45]
}

  pizza_points(customers, 5, 20) ➞ ["Spider-Man"]  
  pizza_points(customers, 3, 10) ➞ ["Batman", "Spider-Man"]  
  pizza_points(customers, 5, 100) ➞ []  

In [27]:
def pizza_points(customers,min_order,min_price):
    orders=0
    eligible = []
    for customer in customers:
        for order_price in customers[customer]:
            if order_price>=min_price:
                orders+=1
        if orders >= min_order:
            eligible.append(customer)
    return eligible

In [28]:
customers = { "Batman": [22, 30, 11, 17, 15, 52, 27, 12], "Spider-Man": [5, 17, 30, 33, 40, 22, 26, 10, 11, 45] }

In [29]:
pizza_points(customers, 5, 20)

['Spider-Man']

In [30]:
pizza_points(customers, 3, 10)

['Batman', 'Spider-Man']

In [31]:
pizza_points(customers, 5, 100)

[]